apiVersion: apps/v1
kind: Deployment
metadata:
  name: rama_cicd
  labels:
    app: rama_cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rama_cicd
  template:
    metadata:
      labels:
        app: rama_cicd
    spec:
      containers:
        - name: rama_cicd
          image: docker.io/raman/rama_cicd:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"

